name: apache-php

services:
  web:
    image: php:8.4.5-apache
    ports:
      - "80:80"
    restart: always
  ftp:
    image: bogem/ftp
    ports:
      - "20:20"
      - "21:21"
      - "47400-47470:47400-47470"
    volumes:
      - /root/www:/home/vsftpd
    restart: always
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASS: ${FTP_PASS}
      PASV_ADDRESS: 192.168.1.65

#      PASV_ADDRESS=<ip of server>
