name: nextcloud

services:
  db:
    image: postgres:latest
    container_name: nextcloud_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /root/postgresql:/var/lib/postgresql/data
    restart: always
  adminer:
    image: adminer
    container_name: nextcloud_postgres_adminer
    restart: always
    ports:
      - 8080:8080
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    environment:
      POSTGRES_HOST: nextcloud_postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '80:80'
    links:
      - db
    volumes:
      - /root/nextcloud:/var/www/html
    restart: always
  ftp:
    image: bogem/ftp
    ports:
      - 20:20
      - 21:21
      - 47400-47470:47400-47470
    volumes:
      - /root/nextcloud:/home/vsftpd
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASS: ${FTP_PASS}
      PASV_ADDRESS: ${PASV_ADDRESS}
    restart: always
