name: apache-php

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - /root/mysql:/var/lib/mysql:Z
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 80:80
#  ftp:
#    image: bogem/ftp
#    ports:
#      - 20:20
#      - 21:21
#      - 47400-47470:47400-47470
#    volumes:
#      - /root/www:/home/vsftpd
#    environment:
#      FTP_USER: ${FTP_USER}
#      FTP_PASS: ${FTP_PASS}
#      PASV_ADDRESS: ${PASV_ADDRESS}
#    restart: always

# docker compose up -d
