name: nginx-proxy-manager

services:
  web:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - /root/letsencrypt:/etc/letsencrypt
      - /root/data:/data
    restart: always
#  ftp:
#    image: bogem/ftp
#    ports:
#      - 20:20
#      - 21:21
#      - 47400-47470:47400-47470
#    volumes:
#      - /root/ftp:/home/vsftpd
#    environment:
#      FTP_USER: ${FTP_USER}
#      FTP_PASS: ${FTP_PASS}
#      PASV_ADDRESS: ${PASV_ADDRESS}
#    restart: always
